version: "3.7"
services:
  web:
    image: nginx:stable
    container_name: wardsonar_web
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - wardsonar-net

  app:
    build:
      context: ./docker
      target: core-app
    container_name: wardsonar_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - wardsonar-net

networks:
  wardsonar-net:
