version: "3.7"
services:
  web:
    image: nginx:latest
    container_name: wardsonar_web
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build: ./docker/php
    image: wardsonar:latest
    container_name: wardsonar_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
